### PR TITLE
Features/ft 409 sort analysis jobs

### PR DESCRIPTION
**Pull request by haarts**
This fixes FT-409.

I also took the liberty of removing some trailing whitespace and fixed some indenting. Also I lowercased some tags.

### CODE REVIEW

**Comment by cataphract** [comment]
Oh, and we use spaces, not tabs, even though there are currently many files that (inconsistently) use tabs. This is also what the Imperial guys use.

See `README-CONVENTIONS.md` on the repository root

**Comment by haarts** [comment]
Yeah, I wanted to discuss that with you. Do you want to search and replace tabs with spaces in files we touch?

**Comment by cataphract** [comment]
Yes, replacing tabs with spaces, removing trailing space and fixing the indentation in a separate commit would be the preferred course of action. In practice, we do it infrequently. Perhaps it would be better to do it en masse (like we did with the line endings), but before our master is taken as the main dev branch in the community (assuming that indeed happens). That would alleviate some merge nuisances with conflicting whitespace.

**Comment by haarts** [comment]
Sounds good! 
I'm now fixing indentation and trailing whitespace and leave the tab as-is for now. Let's discuss when you are feeling better.

**Pull request merged**
